---
authors:
  - Test
dependencies:
  "ansible.netcommon": ">=2.5.1"
license_file: LICENSE
name: test
namespace: test
description: test.
readme: README.md
repository: https://github.com/test-collections/test.test
issues: https://github.com/test-collections/test.test/issues
tags: [tests, test, testing, tested]
version: "1.0.0"
