---
- name: Invoke persist function
  ansible.builtin.include_role:
    name: network.base.resource_manager
  vars:
    operation: "persist"
    resources:
      - acl_interfaces
      - acls
    ignore_empty: "{{ persist_empty | default(true) }}"
