---
- name: Invoke remediate function
  ansible.builtin.include_role:
    name: network.base.resource_manager
  vars:
    operation: "remediate"
    state: "replaced"
    resources:
      - acl_interfaces
      - acls
