# fmt: off
[
  {
    "name": "acls_name", # Extended IP access list 101
    "getval": '''^(?P<afi>ipv4|ipv6)\saccess-list\s(?P<acl_name>.+)$''',
    "result":
      {
        "{{ acl_name|d() }}":
          {
            "name": "{{ acl_name }}",
            "acl_type": "{{ acl_type.lower() if acl_type is defined }}",
            "afi": "{{ 'ipv4' if afi == 'IP' else 'ipv6' }}",
          },
      },
    "shared": True,
  },
  {
    "name": "aces", # \s\s\s40 deny icmp any 10.1.1.0 0.0.0.255 echo
    "getval": '''\s*(?P<sequence>\d+)\s(?P<grant>deny|permit)?.+''',
    "result":
      { "{{ acl_name }}": { "aces": { "{{ sequence }}": "{{ grant }}" } } },
  },
]
# fmt: on
