# fmt: off
[
  {
    "name": "acls_name", # Extended IP access list 101
    "getval": '''^(?P<afi>IP|IPv6|MAC)\saccess\slist\s(?P<acl_name>.+)$''',
    "result":
      {
        "{{ acl_name|d() }}": { "name": "{{ acl_name }}", "afi": "{{ afi }}" },
      },
    "shared": True,
  },
  {
    "name": "aces", # \s\s\s40 deny icmp any 10.1.1.0 0.0.0.255 echo
    "getval": '''\s*(?P<sequence>\d+)\s(?P<grant>deny|permit)?.+''',
    "result":
      { "{{ acl_name }}": { "aces": { "{{ sequence }}": "{{ grant }}" } } },
  },
]
# fmt: on
