---
name: "Draft Release"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
env:
  NAMESPACE: cisco
  COLLECTION_NAME: ios
  ANSIBLE_COLLECTIONS_PATHS: ./
jobs:
  update_release_draft:
    uses: ansible/ansible-github-actions/.github/workflows/draft_release.yaml@main
    with:
      repo: ansible-collections/cisco.ios
    secrets:
      BOT_PAT: ${{ secrets.BOT_PAT }}
