---
name: release
on:  # yamllint disable-line rule:truthy
  release:
    types: [published]

jobs:
  release:
    uses: KB-perByte/ansible-content-action@main
    with:
      environment: release
    secrets:
      ansible_galaxy_api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
