---
name: release
on:  # yamllint disable-line rule:truthy
  release:
    types: [published]

jobs:
  release:
<<<<<<< Updated upstream
    runs-on: ubuntu-latest
    steps:
      - uses: KB-perByte/ansible-content-action@main
        with:
          ansible_galaxy_api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
=======
    uses: ansible/ansible-github-actions@main
    with:
      environment: release
      ansible_galaxy_api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
>>>>>>> Stashed changes
