---
name: test_mono

# concurrency:
#   group: ${{ github.head_ref || github.run_id }}
#   cancel-in-progress: true

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ansible-network/github_actions/.github/actions/checkout_dependency@main

      - name: Run ansible-lint
        uses: KB-perByte/ansible-content-action@main

  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: ansible-network/github_actions/.github/actions/checkout_dependency@main

      - name: Run sanity
        uses: KB-perByte/ansible-content-action@main
